# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/deya/projects/Rubik-s-Cube-Solver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/deya/projects/Rubik-s-Cube-Solver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deya/projects/Rubik-s-Cube-Solver/CMakeFiles /home/deya/projects/Rubik-s-Cube-Solver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deya/projects/Rubik-s-Cube-Solver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Roobik

# Build rule for target.
Roobik: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Roobik
.PHONY : Roobik

# fast build rule for target.
Roobik/fast:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/build
.PHONY : Roobik/fast

src/CoordCube.o: src/CoordCube.cpp.o

.PHONY : src/CoordCube.o

# target to build an object file
src/CoordCube.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/CoordCube.cpp.o
.PHONY : src/CoordCube.cpp.o

src/CoordCube.i: src/CoordCube.cpp.i

.PHONY : src/CoordCube.i

# target to preprocess a source file
src/CoordCube.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/CoordCube.cpp.i
.PHONY : src/CoordCube.cpp.i

src/CoordCube.s: src/CoordCube.cpp.s

.PHONY : src/CoordCube.s

# target to generate assembly for a file
src/CoordCube.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/CoordCube.cpp.s
.PHONY : src/CoordCube.cpp.s

src/CubieCube.o: src/CubieCube.cpp.o

.PHONY : src/CubieCube.o

# target to build an object file
src/CubieCube.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/CubieCube.cpp.o
.PHONY : src/CubieCube.cpp.o

src/CubieCube.i: src/CubieCube.cpp.i

.PHONY : src/CubieCube.i

# target to preprocess a source file
src/CubieCube.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/CubieCube.cpp.i
.PHONY : src/CubieCube.cpp.i

src/CubieCube.s: src/CubieCube.cpp.s

.PHONY : src/CubieCube.s

# target to generate assembly for a file
src/CubieCube.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/CubieCube.cpp.s
.PHONY : src/CubieCube.cpp.s

src/Node.o: src/Node.cpp.o

.PHONY : src/Node.o

# target to build an object file
src/Node.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/Node.cpp.o
.PHONY : src/Node.cpp.o

src/Node.i: src/Node.cpp.i

.PHONY : src/Node.i

# target to preprocess a source file
src/Node.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/Node.cpp.i
.PHONY : src/Node.cpp.i

src/Node.s: src/Node.cpp.s

.PHONY : src/Node.s

# target to generate assembly for a file
src/Node.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/Node.cpp.s
.PHONY : src/Node.cpp.s

src/cubiecube_utils.o: src/cubiecube_utils.cpp.o

.PHONY : src/cubiecube_utils.o

# target to build an object file
src/cubiecube_utils.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/cubiecube_utils.cpp.o
.PHONY : src/cubiecube_utils.cpp.o

src/cubiecube_utils.i: src/cubiecube_utils.cpp.i

.PHONY : src/cubiecube_utils.i

# target to preprocess a source file
src/cubiecube_utils.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/cubiecube_utils.cpp.i
.PHONY : src/cubiecube_utils.cpp.i

src/cubiecube_utils.s: src/cubiecube_utils.cpp.s

.PHONY : src/cubiecube_utils.s

# target to generate assembly for a file
src/cubiecube_utils.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/cubiecube_utils.cpp.s
.PHONY : src/cubiecube_utils.cpp.s

src/heuristics.o: src/heuristics.cpp.o

.PHONY : src/heuristics.o

# target to build an object file
src/heuristics.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/heuristics.cpp.o
.PHONY : src/heuristics.cpp.o

src/heuristics.i: src/heuristics.cpp.i

.PHONY : src/heuristics.i

# target to preprocess a source file
src/heuristics.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/heuristics.cpp.i
.PHONY : src/heuristics.cpp.i

src/heuristics.s: src/heuristics.cpp.s

.PHONY : src/heuristics.s

# target to generate assembly for a file
src/heuristics.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/heuristics.cpp.s
.PHONY : src/heuristics.cpp.s

src/heuristics_tables.o: src/heuristics_tables.cpp.o

.PHONY : src/heuristics_tables.o

# target to build an object file
src/heuristics_tables.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/heuristics_tables.cpp.o
.PHONY : src/heuristics_tables.cpp.o

src/heuristics_tables.i: src/heuristics_tables.cpp.i

.PHONY : src/heuristics_tables.i

# target to preprocess a source file
src/heuristics_tables.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/heuristics_tables.cpp.i
.PHONY : src/heuristics_tables.cpp.i

src/heuristics_tables.s: src/heuristics_tables.cpp.s

.PHONY : src/heuristics_tables.s

# target to generate assembly for a file
src/heuristics_tables.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/heuristics_tables.cpp.s
.PHONY : src/heuristics_tables.cpp.s

src/ida.o: src/ida.cpp.o

.PHONY : src/ida.o

# target to build an object file
src/ida.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/ida.cpp.o
.PHONY : src/ida.cpp.o

src/ida.i: src/ida.cpp.i

.PHONY : src/ida.i

# target to preprocess a source file
src/ida.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/ida.cpp.i
.PHONY : src/ida.cpp.i

src/ida.s: src/ida.cpp.s

.PHONY : src/ida.s

# target to generate assembly for a file
src/ida.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/ida.cpp.s
.PHONY : src/ida.cpp.s

src/ida_utils.o: src/ida_utils.cpp.o

.PHONY : src/ida_utils.o

# target to build an object file
src/ida_utils.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/ida_utils.cpp.o
.PHONY : src/ida_utils.cpp.o

src/ida_utils.i: src/ida_utils.cpp.i

.PHONY : src/ida_utils.i

# target to preprocess a source file
src/ida_utils.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/ida_utils.cpp.i
.PHONY : src/ida_utils.cpp.i

src/ida_utils.s: src/ida_utils.cpp.s

.PHONY : src/ida_utils.s

# target to generate assembly for a file
src/ida_utils.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/ida_utils.cpp.s
.PHONY : src/ida_utils.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/move_tables.o: src/move_tables.cpp.o

.PHONY : src/move_tables.o

# target to build an object file
src/move_tables.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/move_tables.cpp.o
.PHONY : src/move_tables.cpp.o

src/move_tables.i: src/move_tables.cpp.i

.PHONY : src/move_tables.i

# target to preprocess a source file
src/move_tables.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/move_tables.cpp.i
.PHONY : src/move_tables.cpp.i

src/move_tables.s: src/move_tables.cpp.s

.PHONY : src/move_tables.s

# target to generate assembly for a file
src/move_tables.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/move_tables.cpp.s
.PHONY : src/move_tables.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/Roobik.dir/build.make CMakeFiles/Roobik.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Roobik"
	@echo "... src/CoordCube.o"
	@echo "... src/CoordCube.i"
	@echo "... src/CoordCube.s"
	@echo "... src/CubieCube.o"
	@echo "... src/CubieCube.i"
	@echo "... src/CubieCube.s"
	@echo "... src/Node.o"
	@echo "... src/Node.i"
	@echo "... src/Node.s"
	@echo "... src/cubiecube_utils.o"
	@echo "... src/cubiecube_utils.i"
	@echo "... src/cubiecube_utils.s"
	@echo "... src/heuristics.o"
	@echo "... src/heuristics.i"
	@echo "... src/heuristics.s"
	@echo "... src/heuristics_tables.o"
	@echo "... src/heuristics_tables.i"
	@echo "... src/heuristics_tables.s"
	@echo "... src/ida.o"
	@echo "... src/ida.i"
	@echo "... src/ida.s"
	@echo "... src/ida_utils.o"
	@echo "... src/ida_utils.i"
	@echo "... src/ida_utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/move_tables.o"
	@echo "... src/move_tables.i"
	@echo "... src/move_tables.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

